# Generated by Django 5.2.14 on 2026-05-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Unknown User', max_length=255),
            preserve_default=False,
        ),
    ]
